spring:
  application:
    name: toy-project-2024
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
  data:
    redis:
      url: redis://localhost:6379
      timeout: 1s
      connect-timeout: 3s
      client-type: lettuce

jwt:
  secret-key: 01234567890123456789012345678901
  access-token-validity-in-milliseconds: 3600000
  refresh-token-validity-in-milliseconds: 86400000
  access-token-db-check-in-milliseconds: 3600000
