spring:
  datasource:
    url: jdbc:mysql://localhost:3306/redisson
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

logging:
  level:
    org.springframework: DEBUG

redis:
  mode: SINGLE
  nodes:
    - 'redis://localhost:6379'
