server:
  port: 8081

spring:
  application:
    name: toy-project-2024-frontend
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

api-base-url: http://localhost:8080
aes:
  secret: ${AES_SECRET}
  iv: ${AES_IV}
