spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 10
  data:
    redis:
      host: localhost
      port: 6370
      timeout: 1s
      connect-timeout: 3s
      client-type: lettuce
